extends:
  - "airbnb-base"
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "prettier"
  - "prettier/react"
settings:
  react:
    pragma: React
    version: detect
overrides:
  - files: ["*.spec.js"]
    rules:
      "react/display-name": 0
  - files: ["*.spec.js"]
    globals:
      page: true
      HOST: true
rules:
  "prefer-destructuring": 0
  "react/jsx-filename-extension": 0
  "react/destructuring-assignment": 0
